# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codecrafters < Formula
  desc "CodeCrafters CLI"
  homepage "https://codecrafters.io.io"
  version "18"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/codecrafters-io/cli/releases/download/v18/v18_darwin_arm64.tar.gz"
      sha256 "07ae64754d39ca81c62167288869d8f62fe5683cfbacffe06910337fd79cf16a"

      def install
        bin.install "codecrafters"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/codecrafters-io/cli/releases/download/v18/v18_darwin_amd64.tar.gz"
      sha256 "34f45c2625e7c708ab1388b64ef7eb50d94559d24f84276f6ca01ad91c02abbc"

      def install
        bin.install "codecrafters"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codecrafters-io/cli/releases/download/v18/v18_linux_arm64.tar.gz"
      sha256 "05e8b4ac87cdfdd4cd850f977b09e07c5f3721d1a5b3924ddebe2969e5d0c0ba"

      def install
        bin.install "codecrafters"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/codecrafters-io/cli/releases/download/v18/v18_linux_amd64.tar.gz"
      sha256 "bb7266bd63cc71bbdff598f98a2a1535090dfc774c2ef908f93a937c7fcfc1b1"

      def install
        bin.install "codecrafters"
      end
    end
  end
end
